---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mysql
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeName: nfs-mysql
  resources:
    requests:
      storage: 256Mi
