apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mysql
  labels: 
    app: mysql
spec:
  nfs: 
    server: 192.168.2.12
    path: "/NAS/MYSQL"
  mountOptions:
  - hard
  - nfsvers=4.1
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 256Mi
