apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: busybox
    env:
    - name: MESSAGE
      value: "to ja krzys"
    command: ["/bin/sh", "-c"]
    args:
    - echo "Test with ->"; 
      echo $MESSAGE;
      sleep 1m;
