apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: mysql-admin
spec:
  request: $(cat mysql-admin.csr.encoded)
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
